
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ibex_create_buffer
#define yy_delete_buffer ibex_delete_buffer
#define yy_flex_debug ibex_flex_debug
#define yy_init_buffer ibex_init_buffer
#define yy_flush_buffer ibex_flush_buffer
#define yy_load_buffer_state ibex_load_buffer_state
#define yy_switch_to_buffer ibex_switch_to_buffer
#define yyin ibexin
#define yyleng ibexleng
#define yylex ibexlex
#define yylineno ibexlineno
#define yyout ibexout
#define yyrestart ibexrestart
#define yytext ibextext
#define yywrap ibexwrap
#define yyalloc ibexalloc
#define yyrealloc ibexrealloc
#define yyfree ibexfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE ibexrestart(ibexin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int ibexleng;

extern FILE *ibexin, *ibexout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ibextext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up ibextext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via ibexrestart()), so that the user can continue scanning by
	 * just pointing ibexin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when ibextext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int ibexleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow ibexwrap()'s to do buffer switches
 * instead of setting up a fresh ibexin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void ibexrestart (FILE *input_file  );
void ibex_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ibex_create_buffer (FILE *file,int size  );
void ibex_delete_buffer (YY_BUFFER_STATE b  );
void ibex_flush_buffer (YY_BUFFER_STATE b  );
void ibexpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void ibexpop_buffer_state (void );

static void ibexensure_buffer_stack (void );
static void ibex_load_buffer_state (void );
static void ibex_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ibex_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ibex_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ibex_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ibex_scan_bytes (yyconst char *bytes,int len  );

void *ibexalloc (yy_size_t  );
void *ibexrealloc (void *,yy_size_t  );
void ibexfree (void *  );

#define yy_new_buffer ibex_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ibexensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ibex_create_buffer(ibexin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ibexensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ibex_create_buffer(ibexin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *ibexin = (FILE *) 0, *ibexout = (FILE *) 0;

typedef int yy_state_type;

extern int ibexlineno;

int ibexlineno = 1;

extern char *ibextext;
#define yytext_ptr ibextext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up ibextext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	ibexleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 49
#define YY_END_OF_BUFFER 50
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[264] =
    {   0,
        0,    0,   50,   48,   42,   43,   48,   48,   48,   39,
       48,   48,   46,   48,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   42,    0,   36,
       38,    0,   40,   38,   39,    0,   47,   44,   45,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   26,   12,
       37,   37,   35,   37,   37,   37,   37,   37,   37,   37,
        0,    0,    0,   40,   38,   39,    0,   38,   37,   37,

       37,   37,   32,   33,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   10,   37,   37,   37,   37,   37,
       14,   11,   37,   27,    6,   28,    7,   37,   37,   37,
       15,   37,   29,   16,   37,    0,   38,   41,   39,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   17,   18,   19,   37,   37,   20,   37,
       37,   37,   37,    9,   21,   13,   22,   37,   39,   31,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   23,   24,    8,   25,   37,   37,   37,   37,
       37,   37,   38,   37,   37,   37,   37,   37,   37,   37,

       37,   37,   37,   30,   37,   37,   37,   37,   37,   37,
       37,   37,   38,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   38,   37,   37,   37,   37,    4,    5,   37,   37,
       37,   37,   37,   37,   37,   37,   38,    1,   37,   37,
       37,   37,    2,   37,   37,   38,   37,   37,    3,   37,
       38,   34,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    8,    9,   10,   10,   11,
       10,   10,   10,   10,   10,   10,   10,   12,    1,   13,
       14,   15,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   23,   23,   25,   26,   27,   28,   29,
       23,   30,   31,   32,   33,   34,   23,   23,   23,   35,
        1,    1,    1,    1,   23,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   23,   23,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   23,   56,
       23,   57,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[268] =
    {   0,
        0,    0,  363,  364,  360,  364,  357,   48,   55,   55,
      346,  345,  364,  344,    0,   41,   34,   40,   40,   45,
       54,   51,   56,   46,  317,  308,   29,   26,  308,  307,
       42,  305,  316,  311,   52,  314,  313,  346,  343,  342,
       90,  340,    0,   93,   97,  103,  364,  364,  364,    0,
      322,  301,  315,  294,  321,  300,  308,  310,  285,  288,
      307,  286,  302,  280,  298,  276,  298,  276,  274,  277,
      280,  287,  280,   64,  282,  271,  268,  271,  276,    0,
      260,   73,    0,  264,  261,   75,  262,  263,  264,  259,
      117,  304,  299,    0,  108,  121,  115,  124,  283,  262,

      274,  252,    0,    0,  285,  264,  277,  256,  283,  262,
      264,  242,  271,  250,    0,  241,  245,  244,  246,  237,
      245,    0,  249,    0,    0,    0,  242,  249,  230,  236,
      239,  228,    0,  237,  235,  128,  130,  364,  134,  251,
      230,  244,  222,  242,  220,  246,  225,  244,  223,  238,
      216,  250,  229,  221,  220,  104,  215,  208,    0,  207,
      213,  212,  206,    0,    0,    0,    0,  220,  141,    0,
       63,   85,  231,  210,  229,  208,  231,  210,  222,  201,
      230,  209,    0,    0,    0,    0,  107,  201,  200,  203,
      195,  204,  145,  213,  223,  191,  201,  208,  187,  199,

      176,  200,  178,    0,  205,  184,  181,  191,  178,  168,
      171,  178,  149,  190,  197,  167,  175,  191,  170,  195,
      169,  186,  165,  184,  163,  148,  156,  152,  157,  156,
      155,  154,  162,  165,  139,  143,    0,    0,  158,  136,
      155,  132,  131,  135,  129,  127,  158,    0,  144,  118,
      136,  111,    0,  101,   98,  162,  115,   45,    0,   25,
      167,    0,  364,  207,   72,  210,  213
    } ;

static yyconst flex_int16_t yy_def[268] =
    {   0,
      263,    1,  263,  263,  263,  263,  264,  263,  263,  263,
      263,  263,  263,  263,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  263,  264,  264,
      263,  266,  267,  263,  263,  263,  263,  263,  263,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      263,  266,  266,  267,  263,  263,  263,  263,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  263,  263,  263,  263,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  263,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  263,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  263,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  263,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  263,  265,  265,  265,
      265,  265,  265,  265,  265,  263,  265,  265,  265,  265,
      263,  265,    0,  263,  263,  263,  263
    } ;

static yyconst flex_int16_t yy_nxt[422] =
    {   0,
        4,    5,    6,    7,    4,    4,    4,    8,    9,   10,
       10,   11,   12,   13,   14,   15,   16,   17,   15,   18,
       19,   15,   15,   15,   15,   20,   15,   15,   21,   22,
       15,   15,   15,   23,   15,   24,   25,   26,   15,   27,
       28,   15,   15,   29,   30,   31,   15,   32,   33,   15,
       34,   35,   36,   15,   37,   15,   15,   41,   41,   42,
       51,   53,   44,   43,   45,   45,   55,   57,   61,   63,
       65,   67,   58,   77,   50,   75,  262,   81,  194,   78,
       52,   54,   69,   70,   76,   82,   56,   59,   62,   64,
       66,   68,  195,   60,   46,   86,  262,   71,   72,   41,

       41,   87,   95,   95,   44,   88,   96,   96,   97,   97,
      120,  126,   98,   98,  185,  121,  130,   95,   95,  127,
      196,  131,  136,  136,   98,   98,  137,  137,   44,   91,
      139,  139,   91,   98,   98,  197,   46,  137,  137,  137,
      137,   44,  207,  169,  169,  262,  186,   91,   44,  259,
      193,  193,   44,  260,  213,  213,   44,  208,  232,  232,
       46,   44,  259,  247,  247,   44,  259,  256,  256,   44,
      258,  261,  261,   46,   44,  257,  261,  261,  253,  255,
       46,  254,  248,  253,   91,  253,  252,  251,   91,  250,
      248,  249,  248,   91,  246,  245,  238,   91,  237,  244,

      243,   91,  242,  241,  240,  239,   91,   39,  238,   39,
       92,   92,   92,   94,  238,   94,  237,  237,  236,  235,
      234,  233,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      212,  204,  211,  210,  209,  206,  205,  204,  204,  203,
      202,  201,  200,  199,  198,  192,  191,  190,  189,  188,
      187,  170,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  170,  168,  167,
      166,  165,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,

      146,  145,  144,  143,  142,  141,  140,  138,   93,  135,
      134,  133,  132,  129,  128,  125,  124,  123,  104,  122,
      103,  119,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  104,  105,  104,  103,  103,
      102,  101,  100,   99,   93,   40,   40,   38,   90,   89,
       85,   84,   83,   80,   79,   74,   73,   49,   48,   47,
       40,   38,  263,    3,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,

      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263
    } ;

static yyconst flex_int16_t yy_chk[422] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,    8,    9,
       16,   17,   10,    9,   10,   10,   18,   19,   20,   21,
       22,   23,   19,   28,  265,   27,  260,   31,  171,   28,
       16,   17,   24,   24,   27,   31,   18,   19,   20,   21,
       22,   23,  171,   19,   10,   35,  258,   24,   24,   41,

       41,   35,   44,   44,   45,   35,   45,   45,   46,   46,
       74,   82,   46,   46,  156,   74,   86,   95,   95,   82,
      172,   86,   91,   91,   97,   97,   91,   91,   96,   41,
       96,   96,   44,   98,   98,  172,   45,  136,  136,  137,
      137,  139,  187,  139,  139,  257,  156,   95,  169,  255,
      169,  169,  193,  254,  193,  193,  213,  187,  213,  213,
       96,  232,  252,  232,  232,  247,  251,  247,  247,  256,
      250,  256,  256,  139,  261,  249,  261,  261,  246,  245,
      169,  244,  243,  242,  193,  241,  240,  239,  213,  236,
      235,  234,  233,  232,  231,  230,  229,  247,  228,  227,

      226,  256,  225,  224,  223,  222,  261,  264,  221,  264,
      266,  266,  266,  267,  220,  267,  219,  218,  217,  216,
      215,  214,  212,  211,  210,  209,  208,  207,  206,  205,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      192,  191,  190,  189,  188,  182,  181,  180,  179,  178,
      177,  176,  175,  174,  173,  168,  163,  162,  161,  160,
      158,  157,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  135,  134,
      132,  131,  130,  129,  128,  127,  123,  121,  120,  119,
      118,  117,  116,  114,  113,  112,  111,  110,  109,  108,

      107,  106,  105,  102,  101,  100,   99,   93,   92,   90,
       89,   88,   87,   85,   84,   81,   79,   78,   77,   76,
       75,   73,   72,   71,   70,   69,   68,   67,   66,   65,
       64,   63,   62,   61,   60,   59,   58,   57,   56,   55,
       54,   53,   52,   51,   42,   40,   39,   38,   37,   36,
       34,   33,   32,   30,   29,   26,   25,   14,   12,   11,
        7,    5,    3,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,

      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int ibex_flex_debug;
int ibex_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *ibextext;
#line 1 "../src/parser/lexer.l"
#line 2 "../src/parser/lexer.l"

//============================================================================
//                                  I B E X                                   
// File        : Flex input for Ibex lexer
// Author      : Gilles Chabert
// Copyright   : Ecole des Mines de Nantes (France)
// License     : See the LICENSE file
// Created     : Jun 12, 2012
// Last Update : Jun 12, 2012
//============================================================================	

#include <stdlib.h>
#include <stack>
#include <vector>
#include "ibex_Scope.h"
#include "ibex_Interval.h"
#include "ibex_Expr.h"
#include "ibex_SyntaxError.h"
#include "ibex_P_NumConstraint.h"

#include "parser.tab.hh"

namespace ibex {
namespace parser {
extern std::stack<Scope> scopes;

} // end namespace
} // end namespace

int ibex_lineno = 1;

using namespace ibex;
using namespace ibex::parser;

#line 693 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int ibexlex_destroy (void );

int ibexget_debug (void );

void ibexset_debug (int debug_flag  );

YY_EXTRA_TYPE ibexget_extra (void );

void ibexset_extra (YY_EXTRA_TYPE user_defined  );

FILE *ibexget_in (void );

void ibexset_in  (FILE * in_str  );

FILE *ibexget_out (void );

void ibexset_out  (FILE * out_str  );

int ibexget_leng (void );

char *ibexget_text (void );

int ibexget_lineno (void );

void ibexset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ibexwrap (void );
#else
extern int ibexwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( ibextext, ibexleng, 1, ibexout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ibexin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ibexin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, ibexin))==0 && ferror(ibexin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ibexin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int ibexlex (void);

#define YY_DECL int ibexlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after ibextext and ibexleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 38 "../src/parser/lexer.l"


#line 883 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ibexin )
			ibexin = stdin;

		if ( ! ibexout )
			ibexout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ibexensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ibex_create_buffer(ibexin,YY_BUF_SIZE );
		}

		ibex_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of ibextext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 264 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 364 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 40 "../src/parser/lexer.l"
{ return TK_CONST; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "../src/parser/lexer.l"
{ return TK_VARS; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "../src/parser/lexer.l"
{ return TK_PARAM; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "../src/parser/lexer.l"
{ return TK_FUNCTION; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "../src/parser/lexer.l"
{ return TK_MINIMIZE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "../src/parser/lexer.l"
{ return TK_MAX; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "../src/parser/lexer.l"
{ return TK_MIN; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "../src/parser/lexer.l"
{ return TK_ATAN2; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "../src/parser/lexer.l"
{ return TK_SIGN; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "../src/parser/lexer.l"
{ return TK_ABS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "../src/parser/lexer.l"
{ return TK_EXPO; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "../src/parser/lexer.l"
{ return TK_LOG; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "../src/parser/lexer.l"
{ return TK_SQRT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "../src/parser/lexer.l"
{ return TK_COS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "../src/parser/lexer.l"
{ return TK_SIN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "../src/parser/lexer.l"
{ return TK_TAN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "../src/parser/lexer.l"
{ return TK_ACOS; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "../src/parser/lexer.l"
{ return TK_ASIN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "../src/parser/lexer.l"
{ return TK_ATAN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "../src/parser/lexer.l"
{ return TK_COSH; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "../src/parser/lexer.l"
{ return TK_SINH; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "../src/parser/lexer.l"
{ return TK_TANH; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "../src/parser/lexer.l"
{ return TK_ACOSH; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "../src/parser/lexer.l"
{ return TK_ASINH; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "../src/parser/lexer.l"
{ return TK_ATANH; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "../src/parser/lexer.l"
{ return TK_IN;  }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "../src/parser/lexer.l"
{ return TK_INF; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "../src/parser/lexer.l"
{ return TK_MID; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "../src/parser/lexer.l"
{ return TK_SUP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "../src/parser/lexer.l"
{ return TK_RETURN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "../src/parser/lexer.l"
{ return TK_BEGIN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "../src/parser/lexer.l"
{ return TK_END;  }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "../src/parser/lexer.l"
{ return TK_FOR;  }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "../src/parser/lexer.l"
{ return TK_CTRS; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "../src/parser/lexer.l"
{ return TK_INFINITY; } 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "../src/parser/lexer.l"
{ ibexlval.str = (char*) malloc(strlen(ibextext)-1);
                                   /* copy while removing quotes */
                                   strncpy(ibexlval.str,&ibextext[1],strlen(ibextext)-2);   
                                   ibexlval.str[strlen(ibextext)-2]='\0';
                                   return TK_STRING; 
                                 }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 85 "../src/parser/lexer.l"
{ ibexlval.str = (char*) malloc(strlen(ibextext)+1);
                                   strcpy(ibexlval.str,ibextext);
                                   return scopes.top().token(ibextext);				       
                                 }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 89 "../src/parser/lexer.l"
{ 
                                   ibexlval.real = atof(ibextext); return TK_FLOAT; 
                                 }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 92 "../src/parser/lexer.l"
{ ibexlval.itg = atoi(ibextext); return TK_INTEGER; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "../src/parser/lexer.l"
{ /* C++-like comments */ }
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 95 "../src/parser/lexer.l"
{ /* C-like comments */ 
                                   /*strtok (ibextext,"\n");
                                   while (strtok(NULL,"\n")) ++ibex_lineno; */
                                   char* s=ibextext;
                                   while ((s=strpbrk(s,"\n"))) { s+=sizeof(char); ++ibex_lineno; }
                                 }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 102 "../src/parser/lexer.l"
{ /* skipping spaces */ }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 103 "../src/parser/lexer.l"
{ ++ibex_lineno; /* counting CR */ }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 105 "../src/parser/lexer.l"
{ return TK_LEQ; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 106 "../src/parser/lexer.l"
{ return TK_GEQ; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 107 "../src/parser/lexer.l"
{ return TK_EQU; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 108 "../src/parser/lexer.l"
{ return TK_ASSIGN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 109 "../src/parser/lexer.l"
{ return ibextext [0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 110 "../src/parser/lexer.l"
{YY_NEW_FILE; yyterminate();}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 112 "../src/parser/lexer.l"
ECHO;
	YY_BREAK
#line 1232 "<stdout>"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ibexin at a new source and called
			 * ibexlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ibexin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( ibexwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * ibextext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of ibexlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ibexrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			ibexrestart(ibexin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ibexrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 264 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 264 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 263);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up ibextext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					ibexrestart(ibexin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ibexwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve ibextext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void ibexrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ibexensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ibex_create_buffer(ibexin,YY_BUF_SIZE );
	}

	ibex_init_buffer(YY_CURRENT_BUFFER,input_file );
	ibex_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void ibex_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		ibexpop_buffer_state();
	 *		ibexpush_buffer_state(new_buffer);
     */
	ibexensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ibex_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (ibexwrap()) processing, but the only time this flag
	 * is looked at is after ibexwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void ibex_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	ibexin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ibex_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ibexalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ibex_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ibexalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ibex_create_buffer()" );

	b->yy_is_our_buffer = 1;

	ibex_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ibex_create_buffer()
 * 
 */
    void ibex_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ibexfree((void *) b->yy_ch_buf  );

	ibexfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a ibexrestart() or at EOF.
 */
    static void ibex_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	ibex_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ibex_init_buffer was _probably_
     * called from ibexrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void ibex_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ibex_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void ibexpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ibexensure_buffer_stack();

	/* This block is copied from ibex_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ibex_switch_to_buffer. */
	ibex_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void ibexpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ibex_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ibex_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ibexensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)ibexalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ibexensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)ibexrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ibexensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ibex_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ibexalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ibex_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ibex_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to ibexlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ibex_scan_bytes() instead.
 */
YY_BUFFER_STATE ibex_scan_string (yyconst char * yystr )
{
    
	return ibex_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to ibexlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ibex_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ibexalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ibex_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ibex_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ibex_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ibextext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		ibextext[ibexleng] = (yy_hold_char); \
		(yy_c_buf_p) = ibextext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ibexleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ibexget_lineno  (void)
{
        
    return ibexlineno;
}

/** Get the input stream.
 * 
 */
FILE *ibexget_in  (void)
{
        return ibexin;
}

/** Get the output stream.
 * 
 */
FILE *ibexget_out  (void)
{
        return ibexout;
}

/** Get the length of the current token.
 * 
 */
int ibexget_leng  (void)
{
        return ibexleng;
}

/** Get the current token.
 * 
 */

char *ibexget_text  (void)
{
        return ibextext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void ibexset_lineno (int  line_number )
{
    
    ibexlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see ibex_switch_to_buffer
 */
void ibexset_in (FILE *  in_str )
{
        ibexin = in_str ;
}

void ibexset_out (FILE *  out_str )
{
        ibexout = out_str ;
}

int ibexget_debug  (void)
{
        return ibex_flex_debug;
}

void ibexset_debug (int  bdebug )
{
        ibex_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from ibexlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    ibexin = stdin;
    ibexout = stdout;
#else
    ibexin = (FILE *) 0;
    ibexout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * ibexlex_init()
     */
    return 0;
}

/* ibexlex_destroy is for both reentrant and non-reentrant scanners. */
int ibexlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ibex_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		ibexpop_buffer_state();
	}

	/* Destroy the stack itself. */
	ibexfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * ibexlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ibexalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *ibexrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ibexfree (void * ptr )
{
	free( (char *) ptr );	/* see ibexrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 112 "../src/parser/lexer.l"



int ibexwrap () { return 1; }

extern int ibexparse();

void ibexparse_string(const char* syntax) {

	// copy string into new buffer and Switch buffers
	ibex_scan_string (syntax);

	// analyze the string
	try {
	  ibexparse();
	} catch(SyntaxError& e) {
	  // delete the new buffer
	  //ibex_delete_buffer(YY_CURRENT_BUFFER);
      throw(e);
	}

	// delete the new buffer
	//   --> provokes bug when another file is read after...
	//ibex_delete_buffer(YY_CURRENT_BUFFER);
	
}

//"/""*"*([^*]|("*")+[^/])"*"*"/"    { /* C-like comments */ }

