/* WARNING! All changes made to this file will be lost! */

#ifndef W_GAOL_3_1_1_GAOL_GAOL_CONFIGURATION_H_WAF
#define W_GAOL_3_1_1_GAOL_GAOL_CONFIGURATION_H_WAF

/* #undef HAVE_GDTOA_H */
#define GAOL_USING_APMATHLIB 1
#define GAOL_VERBOSE_MODE 1
#define HAVE_VISIBILITY_OPTIONS 1
#define GAOL_PRESERVE_ROUNDING 0
#define GAOL_CERTAINLY_RELATIONS 1
#define GAOL_EXCEPTIONS_ENABLED 1
#define GAOL_USING_ASM 1
#define IX86_CYGWIN 1
#define HAVE_NEXTAFTER 1
#define STDC_HEADERS 1
#define HAVE_FENV_H 1
#define HAVE_FLOAT_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_LIMITS 1
#define HAVE_CASSERT 1
#define INLINE_MACRO 1
#define SIZEOF_INT 4
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG_INT 8
#define HAVE_ROUNDING_MATH_OPTION 1
#define HAVE_FESETROUND 1
#define HAVE_FLOOR 1
#define HAVE_LOCALECONV 1
#define HAVE_MEMSET 1
#define HAVE_POW 1
#define HAVE_SQRT 1
/* #undef HAVE_GETRUSAGE */
#define GETRUSAGE_IN_HEADER 0
#define HAVE_CLOCK 1
#define CLOCK_IN_HEADER 1
#define HAVE___SIGNBIT 1
#define HAVE_ROUND 1
#define HAVE_RINT 1
#define HAVE_FINITE 1

#endif /* W_GAOL_3_1_1_GAOL_GAOL_CONFIGURATION_H_WAF */
