AR = '/usr/bin/ar'
ARFLAGS = 'rcs'
BINDIR = '/usr/local/bin'
BISON = '/usr/bin/bison'
BISONFLAGS = ['-d', '--name-prefix=ibex', '--report=all', '--file-prefix=parser']
BUILD_GAOL = False
BUILD_GDTOA = False
BUILD_MATHLIB = False
CC = ['/usr/bin/gcc']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'gcc'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('4', '7', '2')
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_cshlib = ['-fPIC']
COMPILER_CC = 'gcc'
COMPILER_CXX = 'g++'
CPPPATH_ST = '-I%s'
CXX = ['/usr/bin/g++']
CXXFLAGS = ['-O3', '-Wno-deprecated']
CXXFLAGS_IBEX_DEPS = ['-frounding-math']
CXXFLAGS_MACBUNDLE = ['-fPIC']
CXXFLAGS_cxxshlib = ['-fPIC']
CXXLNK_SRC_F = []
CXXLNK_TGT_F = ['-o']
CXX_NAME = 'gcc'
CXX_SRC_F = []
CXX_TGT_F = ['-c', '-o']
DEFINES = ['NDEBUG=1', 'HAVE_SOPLEX_H=1', 'HAVE_JNI_H=1', 'HAVE_INTERVAL_INTERVAL_HPP=1']
DEFINES_ST = '-D%s'
DEST_BINFMT = 'elf'
DEST_CPU = 'x86_64'
DEST_OS = 'linux'
ENABLE_SHARED = True
FLEX = '/usr/bin/flex'
FLEXFLAGS = ['-t', '-Pibex']
INCLUDES = ['/media/Documents/Etudes/ENSTA-Bretagne/Stages/ENSI3-UFRGS/reliable-slam/workspace/IBEX2.0/soplex-1.7.0/src', '../src/.', '../src/arithmetic', '../src/bisector', '../src/combinatorial', '../src/contractor', '../src/function', '../src/numeric', '../src/parser', '../src/strategy', '../src/symbolic', '../src/tools', '../src/predicate']
INCLUDES_JAVA = ['/usr/lib/jvm/jdk1.7.0_03/include', '/usr/lib/jvm/jdk1.7.0_03/include/linux']
INTERVAL_LIB = 'FILIB'
JAR = '/usr/lib/jvm/jdk1.7.0_03/bin/jar'
JAVAC = '/usr/lib/jvm/jdk1.7.0_03/bin/javac'
JAVAH = '/usr/lib/jvm/jdk1.7.0_03/bin/javah'
JAVA_HOME = ['/usr/lib/jvm/jdk1.7.0_03/']
JAVA_PACKAGE = 'ibex'
LIBDIR = '/usr/local/lib'
LIBPATH = ['3rd', 'src']
LIBPATH_IBEX_DEPS = ['/media/Documents/Etudes/ENSTA-Bretagne/Stages/ENSI3-UFRGS/reliable-slam/workspace/IBEX2.0/soplex-1.7.0/lib']
LIBPATH_JAVA = ['/usr/lib/jvm/jdk1.7.0_03/jre/lib/amd64/server']
LIBPATH_ST = '-L%s'
LIB_IBEX_DEPS = ['soplex', 'z', 'prim']
LIB_JAVA = ['jvm']
LIB_ST = '-l%s'
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cshlib = ['-shared']
LINKFLAGS_cstlib = ['-Wl,-Bstatic']
LINKFLAGS_cxxshlib = ['-shared']
LINKFLAGS_cxxstlib = ['-Wl,-Bstatic']
LINK_CC = ['/usr/bin/gcc']
LINK_CXX = ['/usr/bin/g++']
PREFIX = '/usr/local'
RPATH_ST = '-Wl,-rpath,%s'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
VERSION = '2.0.0alpha'
WITH_JNI = True
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.so'
cstlib_PATTERN = 'lib%s.a'
cxxprogram_PATTERN = '%s'
cxxshlib_PATTERN = 'lib%s.so'
cxxstlib_PATTERN = 'lib%s.a'
define_key = ['NDEBUG', 'HAVE_SOPLEX_H', 'HAVE_JNI_H', 'HAVE_INTERVAL_INTERVAL_HPP']
macbundle_PATTERN = '%s.bundle'
